### PR TITLE
Python packaging

### LINKED ISSUE #3: "Convert" into a proper Python package
- [ ] convert to a proper python package with testing etc
- [ ] `test.py` into neuroconv/tests/basic.py (pytest)

### PR DESCRIPTION
**Pull request by jwodder**
Closes #3.

### CODE REVIEW

**Comment by jwodder** [comment]
Note that someone will need to create a 0.0.0 tag or similar on this repository so that versioneer doesn't fail.

**Comment by yarikoptic** [comment]
@satra Could you please establish the initial version/tag according to your liking so FWIW this PR could be finalized?

**Comment by satra** [comment]
0.1.0 seems reasonable :)

**Comment by yarikoptic** [comment]
uff, ok , created 0.1.0 myself locally, pushed, minted a release from it.

**Comment by jwodder** [comment]
Ping @yarikoptic @satra — This PR is still open.

**Comment by satra** [comment]
@jwodder - should we close this and create one using versioningit ? 

just a note that at this point i think neuroconv is a low priority package, especially given some of the things that @bendichter is doing. but as @thechimera works on conversions this could see more action.

**Comment by jwodder** [comment]
@satra I don't care; I just want to see this PR finished.

**Comment by satra** [comment]
let's merge this in. updates can happen later.

**Pull request merged**
